version: '3.1'

services:
  db:
    container_name: flatmate-db
    image: postgres:latest
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: harrisonbacordo
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flatmate-db
  api:
    container_name: flatmate-api
    image: flatmate-api-image
    restart: always
    environment:
      POSTGRES_USER: harrisonbacordo
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flatmate-db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - .:/code
    depends_on:
      - db
    working_dir: /code
    command: ["fastapi", "dev", "app/main.py"]
    ports:
      - "8000:8000"
